services:
  payments_api:
    build: .
    container_name: payments_api 
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=mysql_payments
      - DB_PORT=3306
      - DB_NAME=labo05_payments_db
      - DB_USER=labo05
      - DB_PASS=labo05
    volumes:
      - .:/app
    ports:
      - "5009:5009"
    networks:
      - labo05-network
    depends_on:
      mysql_payments:
        condition: service_healthy

  mysql_payments:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo05_payments_db
      MYSQL_USER: labo05
      MYSQL_PASSWORD: labo05
    networks:
      - labo05-network
    ports:
      - "3304:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "labo05", "-plabo05"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

networks:
  labo05-network:
    external: true 

volumes:
  mysql_data:
