name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:

      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: labo05_payments_db
          MYSQL_USER: labo05
          MYSQL_PASSWORD: labo05
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3


    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Creer fichier .env
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo05_payments_db" >> .env
          echo "DB_USER=labo05" >> .env
          echo "DB_PASS=labo05" >> .env

      - name: Import DB schema
        run: |
          mysql -h127.0.0.1 -ulabo05 -plabo05 labo05_payments_db < db-init/init.sql

      - name: Run tests
        working-directory: src
        run: python -m pytest --log-cli-level=INFO
